spring:
  config:
    activate:
      on-profile: "prod"
build:
  version: "1.0.0"
cards:
  message: "Welcome to EazyBank Cards related production APIs"
  contactDetails:
    name: "Reine Aishwarya - Product Owner"
    email: "reine@eazybank.com"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384
